package com.virtual_machine;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * 
 * @author arsalan
 */
public class DisplayCommandScreen extends javax.swing.JFrame {

    /**
     * Creates new form Display_Commands
     */
    public DisplayCommandScreen() {
        initComponents();
        this.setPreferredSize(new Dimension(648, 429));
        this.setMaximumSize(new Dimension(648, 429));
        this.setMinimumSize(new Dimension(648, 429));
        this.setBounds(450, 50, 648, 429);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pictures/icon.jpg")));

        ListP.append("\t\t\tList Process\n\n");
        DisplayPCB.setText("\t\t\tDisplay PCB\n\n");
        DisplayPT.setText("\t\t\tDisplay Page Table\n\n");
        MemDump.setText("\t\t\tMemory Dump\n\n");
        FreeFrames.setText("\t\t\tFree Frames\n\n");
        MemDetails.setText("\t\t\tMemory Details\n\n");
        AllotFrames.setText("\t\t\tAllocated Frames\n\n");
        DisplayReg.setText("\t\t\tDisplay Registers\n\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListP = new javax.swing.JTextArea();
        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        DisplayPCB = new javax.swing.JTextArea();
        b2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        DisplayPT = new javax.swing.JTextArea();
        b3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        MemDump = new javax.swing.JTextArea();
        b4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        FreeFrames = new javax.swing.JTextArea();
        b5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MemDetails = new javax.swing.JTextArea();
        b6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllotFrames = new javax.swing.JTextArea();
        b7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        DisplayReg = new javax.swing.JTextArea();
        b8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DINOLIX -> Display Commands");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        ListP.setEditable(false);
        ListP.setBackground(new java.awt.Color(0, 0, 0));
        ListP.setColumns(20);
        ListP.setForeground(new java.awt.Color(255, 255, 255));
        ListP.setRows(5);
        jScrollPane1.setViewportView(ListP);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 600, 250);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(520, 280, 90, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 380);

        jTabbedPane1.addTab("List Process", jPanel1);

        jPanel2.setLayout(null);

        DisplayPCB.setEditable(false);
        DisplayPCB.setBackground(new java.awt.Color(0, 0, 0));
        DisplayPCB.setColumns(20);
        DisplayPCB.setForeground(new java.awt.Color(255, 255, 255));
        DisplayPCB.setRows(5);
        jScrollPane9.setViewportView(DisplayPCB);

        jPanel2.add(jScrollPane9);
        jScrollPane9.setBounds(20, 20, 600, 250);

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);
        b2.setBounds(520, 280, 90, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 410);

        jTabbedPane1.addTab("Display PCB", jPanel2);

        jPanel3.setLayout(null);

        DisplayPT.setEditable(false);
        DisplayPT.setBackground(new java.awt.Color(0, 0, 0));
        DisplayPT.setColumns(20);
        DisplayPT.setForeground(new java.awt.Color(255, 255, 255));
        DisplayPT.setRows(5);
        jScrollPane10.setViewportView(DisplayPT);

        jPanel3.add(jScrollPane10);
        jScrollPane10.setBounds(20, 20, 600, 250);

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel3.add(b3);
        b3.setBounds(520, 280, 90, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 640, 410);

        jTabbedPane1.addTab("Display Page Table", jPanel3);

        jPanel4.setLayout(null);

        MemDump.setEditable(false);
        MemDump.setBackground(new java.awt.Color(0, 0, 0));
        MemDump.setColumns(20);
        MemDump.setForeground(new java.awt.Color(255, 255, 255));
        MemDump.setRows(5);
        jScrollPane5.setViewportView(MemDump);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(20, 20, 600, 250);

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel4.add(b4);
        b4.setBounds(520, 280, 90, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 0, 640, 410);

        jTabbedPane1.addTab("Memory Dump", jPanel4);

        jPanel5.setLayout(null);

        FreeFrames.setEditable(false);
        FreeFrames.setBackground(new java.awt.Color(0, 0, 0));
        FreeFrames.setColumns(20);
        FreeFrames.setForeground(new java.awt.Color(255, 255, 255));
        FreeFrames.setRows(5);
        jScrollPane4.setViewportView(FreeFrames);

        jPanel5.add(jScrollPane4);
        jScrollPane4.setBounds(20, 20, 600, 250);

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel5.add(b5);
        b5.setBounds(520, 280, 90, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(0, 0, 640, 410);

        jTabbedPane1.addTab("Free Frames", jPanel5);

        jPanel6.setLayout(null);

        MemDetails.setEditable(false);
        MemDetails.setBackground(new java.awt.Color(0, 0, 0));
        MemDetails.setColumns(20);
        MemDetails.setForeground(new java.awt.Color(255, 255, 255));
        MemDetails.setRows(5);
        jScrollPane3.setViewportView(MemDetails);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(20, 20, 600, 250);

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel6.add(b6);
        b6.setBounds(520, 280, 90, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel6.add(jLabel7);
        jLabel7.setBounds(0, 0, 640, 410);

        jTabbedPane1.addTab("Memory Details", jPanel6);

        jPanel7.setLayout(null);

        AllotFrames.setEditable(false);
        AllotFrames.setBackground(new java.awt.Color(0, 0, 0));
        AllotFrames.setColumns(20);
        AllotFrames.setForeground(new java.awt.Color(255, 255, 255));
        AllotFrames.setRows(5);
        jScrollPane2.setViewportView(AllotFrames);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(20, 20, 600, 250);

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel7.add(b7);
        b7.setBounds(520, 280, 90, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel7.add(jLabel6);
        jLabel6.setBounds(0, 0, 640, 410);

        jTabbedPane1.addTab("Allocated Frames", jPanel7);

        jPanel8.setLayout(null);

        jPanel9.setLayout(null);

        DisplayReg.setEditable(false);
        DisplayReg.setBackground(new java.awt.Color(0, 0, 0));
        DisplayReg.setColumns(20);
        DisplayReg.setForeground(new java.awt.Color(255, 255, 255));
        DisplayReg.setRows(5);
        jScrollPane11.setViewportView(DisplayReg);

        jPanel9.add(jScrollPane11);
        jScrollPane11.setBounds(20, 20, 600, 250);

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.jpg"))); // NOI18N
        b8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel9.add(b8);
        b8.setBounds(520, 280, 90, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wood-Backgrounds-Picture.jpg"))); // NOI18N
        jPanel9.add(jLabel5);
        jLabel5.setBounds(0, 0, 640, 410);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(0, 0, 640, 410);

        jTabbedPane1.addTab("Display Registers", jPanel8);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 640, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        ListP.setText(null);
        ListP.append("\t\t\tList Process\n\n");
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        DisplayPCB.setText(null);
        DisplayPCB.setText("\t\t\tDisplay PCB\n\n");
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        DisplayPT.setText(null);
        DisplayPT.setText("\t\t\tDisplay Page Table\n\n");
    }//GEN-LAST:event_b3ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        DisplayReg.setText(null);
        DisplayReg.setText("\t\t\tDisplay Registers\n\n");
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        AllotFrames.setText(null);
        AllotFrames.setText("\t\t\tAllocated Frames\n\n");
        //Set_Tab();
    }//GEN-LAST:event_b7ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        MemDetails.setText(null);
        MemDetails.setText("\t\t\tMemory Details\n\n");
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        FreeFrames.setText(null);
        FreeFrames.setText("\t\t\tFree Frames\n\n");
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        MemDump.setText(null);
        MemDump.setText("\t\t\tMemory Dump\n\n");
    }//GEN-LAST:event_b4ActionPerformed
    /**
     * @param args the command line arguments
     */
    /*   public static void main(String args[]) {
     /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*        try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(DisplayCommandScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(DisplayCommandScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(DisplayCommandScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(DisplayCommandScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form */
    /*     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new DisplayCommandScreen().setVisible(true);
     }
     });
     }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea AllotFrames;
    public static javax.swing.JTextArea DisplayPCB;
    public static javax.swing.JTextArea DisplayPT;
    public static javax.swing.JTextArea DisplayReg;
    public static javax.swing.JTextArea FreeFrames;
    public static javax.swing.JTextArea ListP;
    public static javax.swing.JTextArea MemDetails;
    public static javax.swing.JTextArea MemDump;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void Set_Tab(int i) {
        jTabbedPane1.setSelectedIndex(i);
    }

    public void Set_Listp(String str, int i) {
        if (i == 0) {
            ListP.setText(null);
            ListP.append("\t\t\tList Process\n\n");
        } else if (i == 1) {
            ListP.append("\n" + str);
            System.out.println(str);
        }
    }

    public void Set_DisPcb(String str, int i) {
        if (i == 0) {
            DisplayPCB.setText(null);
            DisplayPCB.setText("\t\t\tDisplay PCB\n\n");
        } else if (i == 1) {
            DisplayPCB.append(str);
        }
    }

    public void Set_DisPt(String str, int i) {
        if (i == 0) {
            DisplayPT.setText(null);
            DisplayPT.setText("\t\t\tDisplay Page Table\n\n");
        } else if (i == 1) {
            DisplayPT.append(str);
            System.out.println(str);
        }
    }

    public void Set_DisReg(String str, int i) {
        if (i == 0) {
            DisplayReg.setText(null);
            DisplayReg.setText("\t\t\tDisplay Registers\n\n");

        } else if (i == 1) {
            DisplayReg.append(str);
        }
    }

    public void Set_AllotFrames(String str, int i) {
        if (i == 0) {
            AllotFrames.setText(null);
            AllotFrames.setText("\t\t\tAllocated Frames\n\n");
        } else if (i == 1) {
            AllotFrames.append(str);
            System.out.println(str);
        }
    }

    public void Set_FreeFrames(String str, int i) {
        if (i == 0) {
            FreeFrames.setText(null);
            FreeFrames.setText("\t\t\tFree Frames\n\n");
        } else if (i == 1) {
            FreeFrames.append(str);
            System.out.println(str);
        }
    }

    public void Set_MemDetails(String str, int i) {
        if (i == 0) {
            MemDetails.setText(null);
            MemDetails.setText("\t\t\tMemory Details\n\n");
        } else if (i == 1) {
            MemDetails.append(str);
            System.out.println(str);
        }
    }

    public void Set_MemDump(String str, int i) {
        if (i == 0) {
            MemDump.setText(null);
            MemDump.setText("\t\t\tMemory Dump\n\n");
        } else if (i == 1) {
            MemDump.append(str);
        }
    }
}
